name: db

on:
  repository_dispatch:
    types: db
  workflow_dispatch:
  schedule:
    - cron: 0 17 * * 5

env:
  UPLOAD_RELEASE: true
  FILE_NAME: db

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:    
    - name: Checkout
      uses: actions/checkout@main
    - name: 打包镜像
      uses: unifreq/openwrt_packit@master
      env:
        PACKAGE_SOC: s905d
        WHOAMI: BGG
        OPENWRT_ARMVIRT: https://github.com/0118Add/actions-armbian/releases/download/jarmv8/openwrt-armvirt-64-default-rootfs.tar.gz
        KERNEL_VERSION_NAME: 5.4.170_5.16.2_5.15.15_5.10.93
    - name: upload release
      uses: ncipollo/release-action@v1
      if: env.UPLOAD_RELEASE == 'true' && ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
      with:
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
        allowUpdates: true
        tag: armv8
        token: ${{ secrets.RELEASES_TOKEN }}
        artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
 
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
        
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 3
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
